// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe(" constructor", function() {
  return it("should calculate the winner properly", function() {
    var collection;
    collection = new Deck();
    return assert.strictEqual(collection.length, 52);
  });
});

describe('app', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    return hand = deck.dealPlayer();
  });
  return describe('hit', function() {
    return it('should give the last card from the deck', function() {
      return assert.strictEqual(deck.last(), hand.hit());
    });
  });
});
