// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('deck', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    var hand2;
    deck = new Deck();
    hand = deck.dealPlayer();
    return hand2 = deck.dealDealer();
  });
  return describe('hit', function() {
    it('should give the last card from the deck', function() {
      assert.strictEqual(deck.length, 50);
      assert.strictEqual(deck.last(), hand.hit());
      return assert.strictEqual(deck.length, 49);
    });
    return it('should give the last card from the deck', function() {
      assert.strictEqual(deck.length, 50);
      assert.strictEqual(deck.last(), hand.hit());
      return assert.strictEqual(deck.length, 49);
    });
  });
});
